function New-PSModule {
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([System.IO.DirectoryInfo])]
    param(
        [Parameter(Mandatory, Position = 0)]
        [ValidateNotNullOrEmpty()]
        [string]$Name,

        [Parameter(Position = 1)]
        [string]$Path = (Get-Location).Path,

        [Parameter()]
        [string]$Author = $env:USERNAME,

        [Parameter()]
        [string]$Description = 'PowerShell module generated by PSForge.',

        [Parameter()]
        [string]$CompanyName = 'Community',

        [Parameter()]
        [ValidateSet('MIT')]
        [string]$License = 'MIT',

        [Parameter()]
        [ValidatePattern('^\d+(\.\d+){0,3}$')]
        [string]$PowerShellVersion = '5.1',

        [Parameter()]
        [switch]$Force,

        [Parameter()]
        [switch]$PassThru
    )

    Assert-ValidModuleName -Name $Name

    if (-not $Author) {
        $Author = 'Unknown'
    }

    if (-not (Test-Path -LiteralPath $Path)) {
        $null = New-Item -Path $Path -ItemType Directory -Force
    }

    $destination = Join-Path -Path (Resolve-Path -Path $Path).Path -ChildPath $Name

    if (Test-Path -LiteralPath $destination) {
        $existing = Get-ChildItem -LiteralPath $destination -Force -ErrorAction SilentlyContinue
        if ($existing -and -not $Force) {
            throw "Destination '$destination' already exists and is not empty. Use -Force to overwrite."
        }
        if ($existing -and $Force) {
            if ($PSCmdlet.ShouldProcess($destination, 'Remove existing project directory')) {
                Remove-Item -LiteralPath $destination -Recurse -Force
            }
            else {
                return
            }
        }
    }

    $nounBase = ($Name -replace '[^A-Za-z0-9]', '')
    if ([string]::IsNullOrWhiteSpace($nounBase)) {
        $nounBase = 'Module'
    }
    $sampleFunction = "Get-${nounBase}Example"

    $tokens = @{
        ModuleName        = $Name
        Author            = $Author
        Description       = $Description
        CompanyName       = $CompanyName
        License           = $License
        PowerShellVersion = $PowerShellVersion
        SampleFunction    = $sampleFunction
        Year              = (Get-Date).Year.ToString()
        Guid              = [guid]::NewGuid().ToString()
        Version           = '0.1.0'
    }

    if (-not $PSCmdlet.ShouldProcess($destination, "Scaffold PowerShell module '$Name'")) {
        return
    }

    New-ModuleTree -DestinationPath $destination -Tokens $tokens -SampleFunctionName $sampleFunction
    Write-Verbose "Scaffolded module project at $destination"

    if ($PassThru) {
        Get-Item -LiteralPath $destination
    }
}
